[tool.cibuildwheel.linux]
before-all = "yum install -y openssl-devel"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add openssl-dev"

[tool.cibuildwheel.macos]
before-all = "brew install openssl@1.1"
