name: Build sdist
on: [push]
env:
  CIBW_BUILD_VERBOSITY: 1
jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install deps
      run: python -m pip install build twine
    - name: Build SDist
      run: python -m build --sdist
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*.tar.gz
    - name: Check metadata
      run: twine check dist/*
      
  upload_pypi:
    name: Upload to PyPI (prod)
    needs: [make_sdist]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: wheelhouse/*.whl

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
