name: Build wheel on win64
on: [push]
env:
  CIBW_BUILD_VERBOSITY: 1
  CIBW_ARCHS: "auto64"
  # Run the package tests using `pytest`
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: "pytest --pyargs scrypt"
jobs:

  build_wheels_for_win:
    name: Build wheels on Win64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: install openssl (64 bit)
        shell: pwsh
        run: choco install openssl --limitoutput

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Disable building PyPy wheels
          CIBW_SKIP: pp*
          CIBW_PRERELEASE_PYTHONS: False

      - uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl
 
  upload_pypi:
    name: Upload to PyPI (prod)
    needs: [build_wheels_for_win]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
